### ISSUE TITLE
No support for base graphics

### ISSUE THREAD

**Issue by barryrowlingson** [hafen/rmote#2]
It would be nice if base graphics could be viewed remotely too. Until that time could you highlight that base graphics doesn't work in the README? It only lists the things that do work (lattice, ggplot2 etc).

It might be worth looking to see how knitr handles the detection and capture of base graphics plots...

**Comment by hafen** [comment]
I just pushed up a new version that supports base R graphics.  What makes rmote different from knitr is that rmote is meant for interactive sessions, so it doesn't know when you are done with making a base R plot, whereas in knitr it knows you are done with a plot at the end of a chunk (or the start of a new plot).  

So there's one additional thing you have to do which is when you want the base R plot to show up with rmote, you call `plot_done()`.  There may be a more elegant way handle this but this should suffice for now.

Example:

```
library(rmote)
start_rmote()
browseURL("http://localhost:4321")
plot(1:10)
abline(h = 5)
plot_done()
```
